### ISSUE TITLE
Any support or alternative for `asyncio.Semaphore`?

### ISSUE THREAD

**Issue by NatureGeorge** [alex-sherman/unsync#25]
Hi! Thanks for developing `unsync`, it's a great job. Since I am new to this module and `asyncio` , I am wondering whether there is a way to apply `asyncio.Semaphore` while using `@unsync`? I wrote a program that retrieves data from a API with `unsync` but somehow it went wrong like this:

```txt
File "C:\Users\Nature\Miniconda3\lib\asyncio\locks.py", line 92, in __aenter__
    await self.acquire()
  File "C:\Users\Nature\Miniconda3\lib\asyncio\locks.py", line 474, in acquire
    await fut
RuntimeError: Task <Task pending coro=<fetch_file() running at MyPyCode.py:84>> got Future <Future pending> attached to a different loop
```
After I remove `asyncio.Semaphore` , the program works fine but unable to restrict the coroutine number. The reason that I got to use `asyncio.Semaphore` is to avoid Dos Attack.

## Original Code

```py
import os
from time import perf_counter
import datetime
import asyncio
import aiohttp
import aiofiles
from unsync import unsync

BASE_URL = "https://www.ebi.ac.uk/pdbe/api/pdb/entry/"
DEMO = [
    (BASE_URL+'summary/1a01', '1a01_summary.json'),
    (BASE_URL+'summary/2xyn', '2xyn_summary.json'),
    (BASE_URL+'summary/1miu', '1miu_summary.json'),
    (BASE_URL+'summary/2hev', '2hev_summary.json'),
    (BASE_URL+'summary/3g96', '3g96_summary.json')]

@unsync
async def download_file(url):
    print(f"[{datetime.datetime.now()}] Start to get file: {url}")
    async with aiohttp.ClientSession() as session:
        async with session.get(url) as resp:
            if resp.status == 200:
                return await resp.read()
            elif resp.status == 404:
                return None
            else:
                mes = "code={resp.status}, message={resp.reason}, headers={resp.headers}"
                raise Exception(mes.format(resp=resp))


@unsync
async def save_file(path, data):
    print(f"[{datetime.datetime.now()}] Start to save file: {path}")
    async with aiofiles.open(path, 'wb') as jsonFile:
        await jsonFile.write(data)


@unsync
async def fetch_file(semaphore, url, path, rate):
    async with semaphore:
        data = await download_file(url)
        await asyncio.sleep(rate)
        if data is not None:
            await save_file(path, data)
            return path


def multi_tasks(workdir, concur_req: int, rate=1.5):
    semaphore = asyncio.Semaphore(concur_req)
    tasks = [fetch_file(semaphore, url, os.path.join(workdir, path), rate) for url, path in DEMO]
    for t in tasks:
        t.result()


if __name__ == "__main__":
    workdir = "./"
    t0 = perf_counter()
    multi_tasks(workdir, 4)
    elapsed = perf_counter() - t0
    print(f'downloaded in {elapsed}s')
```

### Behavior (as mentioned above)

```txt
(base) PS C:\GitWorks\temp> python .\MyPyCode.py
[2020-01-16 22:08:59.948408] Start to get file: https://www.ebi.ac.uk/pdbe/api/pdb/entry/summary/1a01
[2020-01-16 22:08:59.972382] Start to get file: https://www.ebi.ac.uk/pdbe/api/pdb/entry/summary/2xyn
[2020-01-16 22:08:59.974339] Start to get file: https://www.ebi.ac.uk/pdbe/api/pdb/entry/summary/1miu
[2020-01-16 22:08:59.975377] Start to get file: https://www.ebi.ac.uk/pdbe/api/pdb/entry/summary/2hev
[2020-01-16 22:09:02.782357] Start to save file: C:\GitWorks\temp\1miu_summary.json
[2020-01-16 22:09:02.783426] Start to save file: C:\GitWorks\temp\2hev_summary.json
[2020-01-16 22:09:02.896178] Start to save file: C:\GitWorks\temp\2xyn_summary.json
[2020-01-16 22:09:02.932120] Start to save file: C:\GitWorks\temp\1a01_summary.json
Traceback (most recent call last):
  File ".\MyPyCode.py", line 60, in <module>
    multi_tasks(workdir, 4)
  File ".\MyPyCode.py", line 54, in multi_tasks
    t.result()
  File "C:\Users\Nature\Miniconda3\lib\site-packages\unsync\unsync.py", line 112, in result
    return self.future.result()
  File ".\MyPyCode.py", line 41, in fetch_file
    async with semaphore:
  File "C:\Users\Nature\Miniconda3\lib\asyncio\locks.py", line 92, in __aenter__
    await self.acquire()
  File "C:\Users\Nature\Miniconda3\lib\asyncio\locks.py", line 474, in acquire
    await fut
RuntimeError: Task <Task pending coro=<fetch_file() running at .\MyPyCode.py:41>> got Future <Future pending> attached to a different loop
```

## Code that removes `asyncio.Semaphore`

> Just modify the following functions and the rest of code is as same as the original code.

```py
@unsync
async def fetch_file(url, path, rate):
    data = await download_file(url)
    await asyncio.sleep(rate)
    if data is not None:
        await save_file(path, data)
        return path

def multi_tasks(workdir, concur_req: int, rate=1.5):
    # semaphore = asyncio.Semaphore(concur_req)
    tasks = [fetch_file(url, os.path.join(
        workdir, path), rate) for url, path in DEMO]
    for t in tasks:
        t.result()
```

### Behavior

```txt
(base) PS C:\GitWorks\temp> python .\MyPyCode.py
[2020-01-16 22:27:25.656445] Start to get file: https://www.ebi.ac.uk/pdbe/api/pdb/entry/summary/1a01
[2020-01-16 22:27:25.685366] Start to get file: https://www.ebi.ac.uk/pdbe/api/pdb/entry/summary/2xyn
[2020-01-16 22:27:25.686413] Start to get file: https://www.ebi.ac.uk/pdbe/api/pdb/entry/summary/1miu
[2020-01-16 22:27:25.688351] Start to get file: https://www.ebi.ac.uk/pdbe/api/pdb/entry/summary/2hev
[2020-01-16 22:27:25.712284] Start to get file: https://www.ebi.ac.uk/pdbe/api/pdb/entry/summary/3g96
[2020-01-16 22:27:28.868901] Start to save file: C:\GitWorks\temp\1miu_summary.json
[2020-01-16 22:27:28.918699] Start to save file: C:\GitWorks\temp\2hev_summary.json
[2020-01-16 22:27:28.921433] Start to save file: C:\GitWorks\temp\1a01_summary.json
[2020-01-16 22:27:28.923428] Start to save file: C:\GitWorks\temp\2xyn_summary.json
[2020-01-16 22:27:28.947356] Start to save file: C:\GitWorks\temp\3g96_summary.json
downloaded in 3.3005259000000002s
```

It is good to see that the program runs very fast, but it would raise a Dos attack with the number of coroutines grows.

## Code that removes `@unsync`

> Just modify the following functions and the rest of code is as same as the original code.

```py
# @unsync
async def download_file(url):
    print(f"[{datetime.datetime.now()}] Start to get file: {url}")
    async with aiohttp.ClientSession() as session:
        async with session.get(url) as resp:
            if resp.status == 200:
                return await resp.read()
            elif resp.status == 404:
                return None
            else:
                mes = "code={resp.status}, message={resp.reason}, headers={resp.headers}"
                raise Exception(mes.format(resp=resp))


# @unsync
async def save_file(path, data):
    print(f"[{datetime.datetime.now()}] Start to save file: {path}")
    async with aiofiles.open(path, 'wb') as jsonFile:
        await jsonFile.write(data)


# @unsync
async def fetch_file(semaphore, url, path, rate):
    async with semaphore:
        data = await download_file(url)
        await asyncio.sleep(rate)
        if data is not None:
            await save_file(path, data)
            return path


def multi_tasks(workdir, concur_req: int, rate=1.5):
    semaphore = asyncio.Semaphore(concur_req)
    '''
    tasks = [fetch_file(semaphore, url, os.path.join(
        workdir, path), rate) for url, path in DEMO]
    for t in tasks:
        t.result()
    '''
    loop = asyncio.get_event_loop()
    tasks = asyncio.gather(*[loop.create_task(fetch_file(semaphore, url, os.path.join(workdir, path), rate))
                             for url, path in DEMO])
    loop.run_until_complete(tasks)
```

### Behavior

```txt
(base) PS C:\GitWorks\temp> python .\MyPyCode.py
[2020-01-16 22:21:28.923504] Start to get file: https://www.ebi.ac.uk/pdbe/api/pdb/entry/summary/1a01
[2020-01-16 22:21:28.948484] Start to get file: https://www.ebi.ac.uk/pdbe/api/pdb/entry/summary/2xyn
[2020-01-16 22:21:28.949433] Start to get file: https://www.ebi.ac.uk/pdbe/api/pdb/entry/summary/1miu
[2020-01-16 22:21:28.950435] Start to get file: https://www.ebi.ac.uk/pdbe/api/pdb/entry/summary/2hev
[2020-01-16 22:21:32.499267] Start to save file: C:\GitWorks\temp\1a01_summary.json
[2020-01-16 22:21:32.499759] Start to save file: C:\GitWorks\temp\1miu_summary.json
[2020-01-16 22:21:32.507789] Start to get file: https://www.ebi.ac.uk/pdbe/api/pdb/entry/summary/3g96
[2020-01-16 22:21:32.542851] Start to save file: C:\GitWorks\temp\2xyn_summary.json
[2020-01-16 22:21:32.546636] Start to save file: C:\GitWorks\temp\2hev_summary.json
[2020-01-16 22:21:35.358457] Start to save file: C:\GitWorks\temp\3g96_summary.json
downloaded in 6.4380731s
```

Although it works well without `unsync`, I would like to apply `unsync`'s mixing methods feature in my job which integrate threads and processes.

## Environment

```json
{
    "platform": "Win10",
    "python": "3.7.1", 
    "aiohttp": "3.6.2",
    "aiofiles": "0.4.0",
    "unsync": "1.2.1"
}
```

**Comment by alex-sherman** [comment]
I think this is just an issue with the way `asyncio.Semaphore` works. Try this:
https://stackoverflow.com/questions/55918048/asyncio-semaphore-runtimeerror-task-got-future-attached-to-a-different-loop

**Comment by NatureGeorge** [comment]
Oh! I see. Something wrong right here:

```py
def multi_tasks(workdir, concur_req: int, rate=1.5):
    # `semaphore` initiated first and got the default event loop
    semaphore = asyncio.Semaphore(concur_req) 
    # following code creates a new event loop?
    tasks = [fetch_file(semaphore, url, os.path.join(workdir, path), rate) for url, path in DEMO]
    for t in tasks:
        t.result()
```

## How to fix

Here comes a new question, how to let each `fetch_file` which decorated with `@unsync` share the same `Semaphore` object? I came up with some kind of stupid way to achieve it.🐵

```py
# TODO: fix multi_tasks()

SEMAPHORE = None


@unsync
async def fetch_file(concur_req, url, path, rate):
    global SEMAPHORE
    if SEMAPHORE is None:
        SEMAPHORE = asyncio.Semaphore(concur_req)
    async with SEMAPHORE:
        data = await download_file(url)
        await asyncio.sleep(rate)
        if data is not None:
            await save_file(path, data)
            return path
```

Anyway, appreciate for your reply!👍 I will try something like `contextvars` latter.

**Comment by alex-sherman** [comment]
I think you can just do something like:
```python
@unsync
async def multi_tasks(workdir, concur_req: int, rate=1.5):
    # `semaphore` initiated in the `unsync` event loop
    semaphore = asyncio.Semaphore(concur_req) 
    await asyncio.gather([fetch_file(semaphore, url, os.path.join(workdir, path), rate) for url, path in DEMO])
```

**Comment by NatureGeorge** [comment]
@alex-sherman I fix the code as you mentioned, it did works! Thanks a lot.🎉

```py
@unsync
async def fetch_file(semaphore, url, path, rate):
    async with semaphore:
        data = await download_file(url)
        await asyncio.sleep(rate)
        if data is not None:
            await save_file(path, data)
            return path


@unsync
async def multi_tasks(workdir, concur_req: int, rate=1.5):
    semaphore = asyncio.Semaphore(concur_req)
    await asyncio.gather(*[fetch_file(semaphore, url, os.path.join(workdir, path),  rate) for url, path in DEMO])


if __name__ == "__main__":
    workdir = "./"
    t0 = perf_counter()
    multi_tasks(workdir, 4).result()
    elapsed = perf_counter() - t0
    print(f'downloaded in {elapsed}s')
```
