### ISSUE TITLE
Decorator problem

### ISSUE THREAD

**Issue by hbe72** [alex-sherman/unsync#32]
See your example of thread_executor.py, and modify that for execution, thus

```python
import time
from unsync import unsync

# Convert synchronous functions into Unfutures to be executed in `unsync.executor`

@unsync
def non_async_function(seconds):
    time.sleep(seconds)
    return 'Run in parallel!'


def main():
    start = time.time()
    tasks = [non_async_function(0.1) for _ in range(10)]
    print([task.result() for task in tasks])
    print('Executed in {} seconds'.format(time.time() - start))

    # Use the decorator on existing functions

    unsync_sleep = unsync(time.sleep)

    start = time.time()
    tasks = [unsync_sleep(0.1) for _ in range(10)]
    print([task.result() for task in tasks])
    print('Executed in {} seconds'.format(time.time() - start))


if __name__ == '__main__':
    main()
```

Running this fails with:
```bash
$ python thread_executor.py 
['Run in parallel!', 'Run in parallel!', 'Run in parallel!', 'Run in parallel!', 'Run in parallel!', 'Run in parallel!', 'Run in parallel!', 'Run in parallel!', 'Run in parallel!', 'Run in parallel!']
Executed in 0.2030332088470459 seconds
Traceback (most recent call last):
  File "thread_executor.py", line 29, in <module>
    main()
  File "thread_executor.py", line 23, in main
    tasks = [unsync_sleep(0.1) for _ in range(10)]
  File "thread_executor.py", line 23, in <listcomp>
    tasks = [unsync_sleep(0.1) for _ in range(10)]
  File "/obscuredpath/venv/lib/python3.8/site-packages/unsync/unsync.py", line 45, in __call__
    self._set_func(args[0])
  File "/obscuredpath/venv/lib/python3.8/site-packages/unsync/unsync.py", line 38, in _set_func
    assert inspect.isfunction(func)
AssertionError
```

In in test_thread_executor.py there is not test case for decorating an existing function with arguments similar to this example, thus the unit tests pass. This example however does not work. Or did I misunderstand something?

**Comment by alex-sherman** [comment]
Thanks for finding this, I fixed it in #33 and made a new release as v1.3 which should be available on PyPi pretty soon.

Let me know if it doesn't work, thanks again!
