### ISSUE TITLE
`BrokenProcessPool` error using function with `cpu_bound=True`

### ISSUE THREAD

**Issue by desmond-dsouza** [alex-sherman/unsync#50]
Code seems to follow the examples, and the `unsync`ed function is in global scope. Is the fact that `lifted` is not global a problem? I tried making it global and it did not seem to help.

```python
import unsync as un
from typing import Callable, List


def parallelize(f: Callable) -> Callable:
    def lifted(series):
        futures: List[un.Unfuture] = [f(i) for i in series]  # type:ignore
        vals = [f.result() for f in futures]
        return vals

    return lifted


import time


@un.unsync(cpu_bound=True)
def slow_inc(n):
    time.sleep(4)
    return n + 1


print(parallelize(slow_inc)([1, 2, 3]))
```

It's a long error trace included below, ending with: **concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.**

I don't _think_ it's user error on my part.

```
(gpt1-py3.11) GPT1 ) /Users/desmond/Documents/code/AI-invest/GPT1/.venv/bin/python /Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py                                           15:30:45
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 129, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 240, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 291, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py", line 23, in <module>
    print(parallelize(slow_inc)([1, 2, 3]))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py", line 7, in lifted
    futures: List[un.Unfuture] = [f(i) for i in series]  # type:ignore
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py", line 7, in <listcomp>
    futures: List[un.Unfuture] = [f(i) for i in series]  # type:ignore
                                  ^^^^
  File "/Users/desmond/Documents/code/AI-invest/GPT1/.venv/lib/python3.11/site-packages/unsync/unsync.py", line 78, in __call__
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 129, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 240, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 291, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py", line 23, in <module>
    print(parallelize(slow_inc)([1, 2, 3]))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py", line 7, in lifted
    futures: List[un.Unfuture] = [f(i) for i in series]  # type:ignore
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py", line 7, in <listcomp>
    futures: List[un.Unfuture] = [f(i) for i in series]  # type:ignore
                                  ^^^^
  File "/Users/desmond/Documents/code/AI-invest/GPT1/.venv/lib/python3.11/site-packages/unsync/unsync.py", line 78, in __call__
    future = unsync.process_executor.submit(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/process.py", line 787, in submit
    self._adjust_process_count()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/process.py", line 746, in _adjust_process_count
    self._spawn_process()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/process.py", line 764, in _spawn_process
    p.start()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 158, in get_preparation_data
    _check_not_importing_main()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 138, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    future = unsync.process_executor.submit(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/process.py", line 787, in submit
    self._adjust_process_count()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/process.py", line 746, in _adjust_process_count
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 129, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 240, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 291, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py", line 23, in <module>
    print(parallelize(slow_inc)([1, 2, 3]))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py", line 7, in lifted
    futures: List[un.Unfuture] = [f(i) for i in series]  # type:ignore
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/desmond/Docume    self._spawn_process()
nts/code/AI-invest/GPT1/src/unsync_bug.py", line 7, in <listcomp>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/process.py", line 764, in _spawn_process
    p.start()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    futures: List[un.Unfuture] = [f(i) for i in series]  # type:ignore
                                  ^^^^
  File "/Users/desmond/Documents/code/AI-invest/GPT1/.venv/lib/python3.11/site-packages/unsync/unsync.py", line 78, in __call__
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
    future = unsync.process_executor.submit(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/process.py", line 787, in submit
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    self._adjust_process_count()
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/process.py", line 746, in _adjust_process_count
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 158, in get_preparation_data
    self._spawn_process()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/process.py", line 764, in _spawn_process
    _check_not_importing_main()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 138, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    p.start()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 158, in get_preparation_data
    _check_not_importing_main()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 138, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "/Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py", line 23, in <module>
    print(parallelize(slow_inc)([1, 2, 3]))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py", line 8, in lifted
    vals = [f.result() for f in futures]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py", line 8, in <listcomp>
    vals = [f.result() for f in futures]
            ^^^^^^^^^^
  File "/Users/desmond/Documents/code/AI-invest/GPT1/.venv/lib/python3.11/site-packages/unsync/unsync.py", line 144, in result
    return self.concurrent_future.result(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
Future exception was never retrieved
future: <Future finished exception=BrokenProcessPool('A process in the process pool was terminated abruptly while the future was running or pending.')>
Traceback (most recent call last):
  File "/Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py", line 23, in <module>
    print(parallelize(slow_inc)([1, 2, 3]))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py", line 8, in lifted
    vals = [f.result() for f in futures]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py", line 8, in <listcomp>
    vals = [f.result() for f in futures]
            ^^^^^^^^^^
  File "/Users/desmond/Documents/code/AI-invest/GPT1/.venv/lib/python3.11/site-packages/unsync/unsync.py", line 144, in result
    return self.concurrent_future.result(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
Future exception was never retrieved
future: <Future finished exception=BrokenProcessPool('A process in the process pool was terminated abruptly while the future was running or pending.')>
Traceback (most recent call last):
  File "/Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py", line 23, in <module>
    print(parallelize(slow_inc)([1, 2, 3]))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py", line 8, in lifted
    vals = [f.result() for f in futures]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py", line 8, in <listcomp>
    vals = [f.result() for f in futures]
            ^^^^^^^^^^
  File "/Users/desmond/Documents/code/AI-invest/GPT1/.venv/lib/python3.11/site-packages/unsync/unsync.py", line 144, in result
    return self.concurrent_future.result(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
Future exception was never retrieved
future: <Future finished exception=BrokenProcessPool('A process in the process pool was terminated abruptly while the future was running or pending.')>
Traceback (most recent call last):
  File "/Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py", line 23, in <module>
    print(parallelize(slow_inc)([1, 2, 3]))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py", line 8, in lifted
    vals = [f.result() for f in futures]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/desmond/Documents/code/AI-invest/GPT1/src/unsync_bug.py", line 8, in <listcomp>
    vals = [f.result() for f in futures]
            ^^^^^^^^^^
  File "/Users/desmond/Documents/code/AI-invest/GPT1/.venv/lib/python3.11/site-packages/unsync/unsync.py", line 144, in result
    return self.concurrent_future.result(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

**Comment by alex-sherman** [comment]
I'm not sure why the error is long, but hidden in the middle is the problem:
```
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

It works if you do:
```python
if __name__ == '__main__':
  print(parallelize(slow_inc)([1, 2, 3]))
```
